# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "tmwalter98/knative-slack-bolt"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "${{IMAGE_NAME}}"
    working_directory: "${{clone}}"
    tag: "${{CF_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"

  push:
    stage: "push"
    title: Push Docker image to ECR
    type: push
    image_name: "${{IMAGE_NAME}}"
    tags:
      - "latest"
      - "${{CF_REVISION}}"
    candidate: ${{build}}
    registry: "${{IMAGE_NAME}}"

  MyDeploy:
    title: K8s Deploy
    image: codefresh/cf-deploy-kubernetes:master
    commands:
      - /cf-deploy-kubernetes deployment.yml
    environment:
      - KUBECONTEXT=my-cluster-name
      - KUBERNETES_NAMESPACE=my-namespace
# export GIT_TOKEN=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
