apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-slack-bolt
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: docker.io/library/tmwalter98/knative-slack-bolt:latest
          env:
            - name: SLACK_BOT_TOKEN
              value: "xoxb-"
            - name: SLACK_APP_TOKEN
              value: "xapp-"
