apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-slack-bolt
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "{{ .Values.minScale }}"
        autoscaling.knative.dev/max-scale: "{{ .Values.maxScale }}"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SLACK_BOT_TOKEN
              value: "{{ .Values.slackBotToken }}"