apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-slack-bolt
  namespace: knative
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: tmwalter98/knative-slack-bolt:latest
          imagePullPolicy: Always
          env:
            - name: SLACK_BOT_TOKEN
              value: "xoxb-"
            - name: SLACK_APP_TOKEN
              value: "xapp-"
            - name: POSTGRES_URL
              value: "postgresql://username:password@host/database"
            - name: CHANNEL_ID
              value: "A00B00C0DEF"
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-topic-source
  namespace: knative
spec:
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka_broker
          key: user
      password:
        secretKeyRef:
          name: kafka_broker
          key: password
      type:
        secretKeyRef:
          name: kafka_broker
          key: saslType
    tls:
      enable: true
  initialOffset: earliest
  bootstrapServers: []
  topics: []
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-slack-bolt
    uri: /cloudevents