name: Build and Push to Docker Hub

on:
  workflow_dispatch:
    inputs:
        branch_name:
          description: 'Branch name'
          required: true
          default: 'main'
        image_tag:
          description: 'Image tag'
          required: false
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Set image tag
        id: set_tag
        run: echo "::set-output name=tag::${{ github.event.inputs.image_tag || 'latest' }}"

      - name: Set branch name
        id: set_branch
        run: echo "::set-output name=branch::${{ github.event.inputs.branch_name || 'main' }}"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.set_branch.outputs.branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

